---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: LoadBalancer
  selector:
    app: apache-app
  ports:
    - nodePort: 30010
      port: 8000
      protocol: TCP
      targetPort: 80
  externalIPs: 
    - 172.31.93.242