---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-apache-deployment
  labels:
    app: apache-app
    deployment: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-app
  template:
    metadata:
      labels:
        app: apache-app
        deployment: green
    spec:
      containers:
      - name: apache-test
        image: annantguptacs15/apache-test:latest
        ports:
        - containerPort: 80